CREATE TABLE [dbo].[Product]
(
    [Id] INT NOT NULL IDENTITY(0,1) PRIMARY KEY,
	[Designation] NVARCHAR(50) NOT NULL, 
    [EAN] BIGINT NOT NULL DEFAULT 1111111111111, 
    [Name] NVARCHAR(256) NOT NULL, 
    [Type] NVARCHAR(256) NOT NULL, 
    [CreatedDate] DATETIME2 NOT NULL DEFAULT getutcdate(), 
    [LastModified] DATETIME2 NOT NULL DEFAULT getutcdate()
    
)
